version: '1.0'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:blog
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

  backend:
    build: server/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=blog
    env_file:
      - ./server/.env
    depends_on:
      - db

  frontend:
    build: client/
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - backend
